name: "@org/development"

services:
  postgres:
    image: postgres:17-alpine
    volumes:
      - ../../.dockerVolume/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-36122}:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: unless-stopped

  redis:
    image: valkey/valkey:7
    volumes:
      - ../../.dockerVolume/valkey:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    ports:
      - ${REDIS_PORT:-16222}:6379
    entrypoint: sh
    command: -c "valkey-server --appendonly yes --save 60 1 --requirepass ${REDIS_PASSWORD:-password} --loglevel warning"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  s3:
    image: minio/minio
    volumes:
      - ../../.dockerVolume/s3:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-dev}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
    ports:
      # BUCKET
      - ${MINIO_BUCKET_PORT:-33220}:9000
      # WEB
      - ${MINIO_WEB_PORT:-33221}:9001
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://s3:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  s3-entrypoint:
    image: minio/mc
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-dev}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
    depends_on:
      s3:
        condition: service_healthy
    entrypoint: /bin/sh -c "
      /usr/bin/mc config host add minio http://s3:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/private;
      /usr/bin/mc mb minio/public;
      /usr/bin/mc policy set download minio/public;
      /usr/bin/mc anonymous set download minio/public;
      exit 0;"

  inbucket:
    image: inbucket/inbucket
    ports:
      # WEB
      - ${INBUCKET_WEB_PORT:-30180}:9000
      # SMTP
      - ${INBUCKET_SMTP_PORT:-30122}:2500
      # POP
      - ${INBUCKET_POP_PORT:-30170}:1100
    restart: unless-stopped
